/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *STRING CONSTANTS FOR XML PROPERTIES SO THAT ALL TEXT CAN BE LOADED FROM A SINGLE XML FILE
 * 
 *THESE ARE FOR THE NODES WITHIN THE WORKSPACE OF THE APP, NOT FOR THE APPLICATION UI.
 * @author Andrew
 */
public enum CSGProp {
     // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    //OVERALL WORKSPACE TEXT CONTROLS
    TAB1_TITLE,
    TAB2_TITLE,
    TAB3_TITLE,
    TAB4_TITLE,
    TAB5_TITLE,
    ADD_EDIT_TITLE,
    
    ABOUT_TITLE,
    ABOUT_HEADER,
    ABOUT_BLURB,
    
    //COURSEDETAILS TEXT STUFF
    COURSEINFO_TITLE,
    SUBCOURSEINFO1_SUBJECT,
    SUBCOURSEINFO1_NUMBER,
    SUBCOURSEINFO2_SEMESTER,
    SUBCOURSEINFO2_YEAR,
    COURSE_TITLE,
    COURSE_INSTRUCTOR_NAME,
    COURSE_INSTRUCTOR_HOME,
    COURSE_EXPORT_DIR,
    CHANGE_BUTTON_TEXT,
    
    SITE_TEMPLATE_TITLE,
    SITE_TEMPLATE_MESSAGE,
    SITE_TEMPLATE_BUTTON_TEXT,
    SITE_PAGES,
    USE_HEADER_TEXT,
    NAV_BAR_TITLE_TEXT,
    FILE_NAME_HEADER_TEXT,
    SCRIPT_HEADER_TEXT,
    
    
    PAGE_STYLE_TITLE,
    BANNER_SCHOOL_IMAGE,
    LEFT_FOOTER_IMAGE,
    RIGHT_FOOTER_IMAGE,
    STYLESHEET_SELECTOR,
    STYLE_NOTICE,
    
    INVALID_DIRECTORY_MESSAGE,
    INVALID_DIRECTORY_TITLE,
    SELECT_TEMPLATE_TITLE,
    PICK_IMAGE_TITLE,
    
    
    //RECITATION TAB TEXT STUFF
    RECITATION_TITLE,
    SECTION_HEADER_TEXT,
    INSTRUCTOR_HEADER_TEXT,
    REC_DAY_TIME_HEADER_TEXT,
    LOCATION_HEADER_TEXT,
    TA1_HEADER_TEXT,
    TA2_HEADER_TEXT,
    RECITATION_LABEL,
    SECTION_LABEL,
    INSTRUCTOR_LABEL,
    REC_DAY_TIME_LABEL,
    LOCATION_LABEL,
    TA1_LABEL,
    TA2_LABEL,
    ADD_UPDATE_BUTTON_TEXT,
    
    ADD_BUTTON_TEXT_GENERIC,
    UPDATE_BUTTON_TEXT_GENERIC,
    
    INVALID_ENTRY_TITLE,
    EMPTY_SECTION_MESSAGE,
    EMPTY_INSTRUCTOR_MESSAGE,
    EMPTY_DAYTIME_MESSAGE,
    EMPTY_LOCATION_MESSAGE,
    
    E_EMPTY_SECTION_MESSAGE,
    E_EMPTY_INSTRUCTOR_MESSAGE,
    E_EMPTY_DAYTIME_MESSAGE,
    E_EMPTY_LOCATION_MESSAGE,
    
    //SCHEDULES TAB TEXT STUFF
    SCHEDULE_TITLE,
    CALENDAR_BOUNDARIES_TITLE,
    SCHEDULE_STARTING_DAY_TEXT,
    SCHEDULE_ENDING_DAY_TEXT,
    SCHEDULE_ITEMS_TITLE,
    TYPE_HEADER_TEXT,
    DATE_SCHED_HEADER_TEXT,
    TITLE_HEADER_TEXT,
    TOPIC_HEADER_TEXT,
    TYPE_LABEL,
    TYPE_CHOICE_HOLIDAY,
    TYPE_CHOICE_LECTURE,
    TYPE_CHOICE_REFERENCE,
    TYPE_CHOICE_RECITATION,
    TYPE_CHOICE_HW,
    DATE_LABEL,
    TIME_LABEL,
    TITLE_LABEL,
    TOPIC_LABEL,
    LINK_LABEL,
    CRITERIA_LABEL,
    
    INVALID_START_DAY_TITLE,
    INVALID_START_DAY_MESSAGE,
    INVALID_END_DAY_TITLE,
    INVALID_END_DAY_MESSAGE,
    NOT_FRIDAY_TITLE, NOT_FRIDAY_MESSAGE,
    NOT_MONDAY_TITLE,
    NOT_MONDAY_MESSAGE,
    
    ILLEGAL_SCHEDULE_DATA_TITLE,
    ILLEGAL_SCHEDULE_DATA_MESSAGE,
    INVALID_SCHEDULE_ENTRY_TITLE,
    INVALID_SCHEDULE_ENTRY_MESSAGE,
    
    //PROJECTS TAB TEXT STUFF
    PROJECTS_TITLE,
    TEAMS_TITLE,
    TEAM_NAME_HEADER_TEXT,
    TEAM_COLOR_HEADER_TEXT,
    TEAM_TEXT_COLOR_HEADER_TEXT,
    TEAM_LINK_HEADER_TEXT,
    TEAM_NAME_LABEL,
    TEAM_COLOR_LABEL,
    TEAM_TEXT_COLOR_LABEL,
    TEAM_LINK_LABEL,
    
    STUDENTS_TITLE,
    STUDENT_FIRST_HEADER_TEXT,
    STUDENT_LAST_HEADER_TEXT,
    STUDENT_TEAM_HEADER_TEXT,
    STUDENT_ROLE_HEADER_TEXT,
    STUDENT_FIRST_LABEL,
    STUDENT_LAST_LABEL,
    STUDENT_TEAM_LABEL,
    STUDENT_ROLE_LABEL,
    
    TEAM_REMOVE_WARNING_TITLE,
    TEAM_REMOVE_WARNING_MESSAGE,
    
    INVALID_TEAM_TITLE,
    INVALID_TEAM_MESSAGE,
    INVALID_COLOR_TITLE,
    INVALID_COLOR_MESSAGE,
    INVALID_LINK_TITLE,
    INVALID_LINK_MESSAGE,
    INVALID_TEAM_DUPLICATE_MESSAGE,
    
    EDIT_TEAM_WARNING_TITLE,
    EDIT_TEAM_WARNING_MESSAGE,
    
    INVALID_FIRSTNAME_TITLE,
    INVALID_FIRSTNAME_MESSAGE,
    INVALID_LASTNAME_TITLE,
    INVALID_LASTNAME_MESSAGE,
    INVALID_STUDENTTEAM_TITLE,
    INVALID_STUDENTTEAM_MESSAGE,
    INVALID_ROLE_TITLE,
    INVALID_ROLE_MESSAGE,
    
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S TEACHING ASSISTANT SECTION OF WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    UNDERGRAD_COLUMN_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    CLEAR_BUTTON_TEXT,
    
    DELETE_BUTTON_TEXT,
    
    SUBMIT_BUTTON_TEXT,
    START_TIME_TEXT,
    END_TIME_TEXT,
    COMBO_BOX_HEADER_LABEL_TEXT,
    
    REMOVE_TA_WARNING_TITLE,
    REMOVE_TA_WARNING_MESSAGE,
    EDIT_TA_WARNING_TITLE,
    EDIT_TA_WARNING_MESSAGE,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    
    INVALID_TA_EMAIL_FORMAT_TITLE,
    INVALID_TA_EMAIL_FORMAT_MESSAGE, 
    
}
